services:
  sophie-frontend:
    platform: linux/amd64
    image:  softvence/sophie-frontend:latest
    container_name: sophie_frontend
    restart: alwayes
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - VITE_BASE_URL=${VITE_BASE_URL}
    networks:
      - sophie-server_network
    depends_on:
      - server
networks:
  sophie-networks:
    driver: bridge
    external: true
